# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wellness.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_wellness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_QR',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_wellness.Event')),
                ('qr', models.ImageField(blank=True, null=True, upload_to=wellness.models.qr_directory_path, verbose_name='QR Code')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('api_wellness.event',),
        ),
    ]
