# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_auto_20160829_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_event', models.IntegerField(choices=[(1, 'Created'), (2, 'Deleted'), (3, 'Approved'), (4, 'Declined'), (5, 'Checked out'), (6, 'Checked in'), (7, 'Resaved'), (8, 'Resaved and Checked out')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reservations.Reservation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
