# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='reservations.Reservation'),
        ),
    ]
