# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20161130_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='log',
            name='log_event',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Deleted'), (3, 'Approved'), (4, 'Declined'), (5, 'Checked out'), (6, 'Checked in'), (7, 'Saved')]),
        ),
    ]
