# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_auto_20161201_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='reservation',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='reservations.Reservation'),
            preserve_default=False,
        ),
    ]
