# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20161207_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='reservations.Reservation'),
        ),
    ]
