# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_of_seats', models.PositiveSmallIntegerField()),
                ('contact', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('committee_type', models.CharField(choices=[('ACAD', 'Academic Senate Committee'), ('UNIV', 'University Committee')], default='ACAD', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='reporting.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('business', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reports', to='reporting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('chair_email', models.EmailField(max_length=254, verbose_name="ASI Board Chair's Email")),
                ('committees', models.ManyToManyField(blank=True, related_name='representatives', to='reporting.Committee')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_reports', to='reporting.Representative'),
        ),
    ]
