# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='schedule',
            field=models.TextField(default=''),
        ),
    ]
