# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='workorders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='workorders.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('title', models.CharField(choices=[('C', 'Client'), ('D', 'Designer'), ('S', 'Supervisor')], default='C', max_length=1)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workorders.Department')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending Approval'), (2, 'Not Started'), (3, 'In Progress'), (4, 'On Hold'), (5, 'Completed'), (6, 'Cancelled')], default=2)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_workorders', to='workorders.User')),
            ],
            options={
                'permissions': (('approve_workorders', 'Approve work orders'), ('decline_workorders', 'Decline work orders')),
            },
        ),
        migrations.CreateModel(
            name='WorkOrder_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.Product')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.WorkOrder')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='products',
            field=models.ManyToManyField(related_name='workorders', through='workorders.WorkOrder_Products', to='workorders.Product'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_workorders', to='workorders.User'),
        ),
        migrations.AddField(
            model_name='package_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.Product'),
        ),
        migrations.AddField(
            model_name='package',
            name='products',
            field=models.ManyToManyField(related_name='packages', through='workorders.Package_Products', to='workorders.Product'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimensions', to='workorders.Product'),
        ),
        migrations.AddField(
            model_name='asset',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='workorders.WorkOrder'),
        ),
    ]
